version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo 'export TAG=2.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=woolf' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t imogenhardy/$IMAGE_NAME:$TAG -t imogenhardy/$IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push imogenhardy/$IMAGE_NAME:$TAG
            docker push imogenhardy/$IMAGE_NAME:latest
      - add_ssh_keys:
          fingerprints:
            - '7a:f2:f7:9a:6d:30:88:b3:fd:bc:3b:79:d9:74:97:a3'
      - run:
          name: Deploy app to Digital Ocean
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET "source ~/.bashrc && sh ./woolf-runner.sh"
