version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=woolf' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t imogenhardy/$IMAGE_NAME:$TAG -t imogenhardy/$IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push imogenhardy/$IMAGE_NAME:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build
